- README.md
- jest.config.js
- packages/android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts
- packages/flipper-plugin-android-performance-profiler/src/__tests__/Plugin.ts
| Before  | After |
| ------------- | ------------- |
| <img width="873" alt="image" src="https://user-images.githubusercontent.com/40902940/183097141-d353cb70-3b17-43d6-905e-0c16765ffd05.png"> | <img width="616" alt="image" src="https://user-images.githubusercontent.com/40902940/183097215-ba4fa247-e984-4639-83cf-960dc19c76cf.png"> |
> Automatically enable fps debug while running a test

- README.md
- packages/android-performance-profiler/src/commands/__tests__/detectCurrentAppBundleId.test.ts
- packages/android-performance-profiler/src/commands/cpu/getCpuStatsByProcess.ts
- packages/android-performance-profiler/src/commands/detectCurrentAppBundleId.ts
- packages/android-performance-profiler/src/commands/pollPerformanceMeasures.ts
Closes #15 
Duplicate of #18 to run CI on this repo.
The goal is to replace "com.app.any" in the Threads View by "UI Thread".
~~I wanted to use `detectCurrentAppBundleId` in `packages/android-performance-profiler/src/commands/cpu/getCpuStatsByProcess.ts` but it crashed the e2e-test because the app was not detected each time the function was called. I think it is because we close and open the app a lot during our tests.~~
~~So I pass the bundle id in params. I don't know if this is the cleanest way.~~
It was not working for big bundle id like `com.facebook.katana` or bigger. So, I used an other method that is to compare `processId` and `pid`. If these ids are the same, it is the main thread and we write "UI thread".
I manually tested the result on the reporter and it works fine!
I also ran …
> Change UI thread naming

- packages/web-reporter/openReport.ts
Using `process.cwd()` was unnecessary, plus it was breaking absolute paths
For instance when running `npx @perf-profiler/web-reporter /tmp/my-folder`, the script would try to open `/Users/almouro/dev/projects/my-project//tmp/my-folder` instead of `tmp/my-folder` directly
> fix(web-reporter): fix running web-reporter with absolute path

- packages/flipper-plugin-android-performance-profiler/package.json
- packages/flipper-plugin-android-performance-profiler/src/__tests__/__snapshots__/Plugin.ts.snap
- packages/web-reporter-ui/components/CircularProgressWithLabel.tsx
I used what was done [here](https://github.com/bamlab/react-native-flipper-performance-monitor/blob/master/flipper-desktop/src/components/CircularProgressWithLabel.tsx).
There is a problem with `josefin-sans` font-family. See [this issue](https://github.com/google/fonts/issues/3348).
| Before | After |
| ------ | ----- |
| <img width="105" alt="image" src="https://user-images.githubusercontent.com/40902940/190934996-bf157673-c3c1-47a7-91fe-44c1986e4582.png"> | <img width="111" alt="image" src="https://user-images.githubusercontent.com/40902940/190934976-6b128b8d-851e-4029-a896-cef0da01f7f4.png"> |
> fix(web-reporter-ui): remove the uncentered font

- README.md
- packages/appium-helper/AppiumDriver.ts
- packages/e2e-example/basic.ts
- yarn.lock
Closes #21 
With monkey command, we don't need to specify AppActivity to start the app. It avoid security exceptions when we don't know the good AppActivity.
It doesn't seem slower:
| Before | Now |
| ------  |  ---- |
| <img width="262" alt="Capture d’écran 2022-09-19 à 01 56 34" src="https://user-images.githubusercontent.com/40902940/190933902-73527bdc-6266-47be-bc84-67bd47eb014b.png"> | <img width="259" alt="Capture d’écran 2022-09-19 à 01 53 38" src="https://user-images.githubusercontent.com/40902940/190933913-738acb83-0aab-4e9a-8976-a90c5babd64b.png"> |
And the test doesn't seem broken:
> fix(adb): replace start command by monkey

- packages/android-performance-profiler/src/commands/cppProfiler.ts
It would seem that Android < 7 is not supported by the tool. We throw an error if the SDK version is less than 24. 
Issue: https://github.com/bamlab/android-performance-profiler/issues/34
> feat(cppProfiler): throw an error if SDK version is less than 24

- packages/e2e-performance/src/bin.ts
Sadly missing the typings on `commander`
> fix(e2e): fix resultsFilePath parameter

- packages/e2e-performance/src/executeAsync.ts
Now both macOS and ubuntu behave the same when testCommand throws error
> fix(e2e): fail command if e2e test fails on linux

- packages/android-performance-profiler/src/commands/__tests__/detectCurrentAppBundleId.test.ts
- packages/android-performance-profiler/src/commands/__tests__/dumpsys-window.txt
- packages/android-performance-profiler/src/commands/atrace/pollFpsUsage.ts
- packages/android-performance-profiler/src/commands/cppProfiler.ts
- packages/android-performance-profiler/src/commands/cpu/getCpuStatsByProcess.ts
- packages/android-performance-profiler/src/commands/detectCurrentAppBundleId.ts
- packages/android-performance-profiler/src/commands/getAbi.ts
- packages/android-performance-profiler/src/commands/getPidId.ts
- packages/android-performance-profiler/src/commands/gfxInfo/parseGfxInfo.ts
- packages/android-performance-profiler/src/commands/gfxInfo/pollFpsUsage.ts
- packages/e2e-performance/src/executeAsync.ts
- packages/flipper-plugin-android-performance-profiler/src/__tests__/Plugin.ts
- packages/web-reporter/openReport.ts
What's working
(➡️ Need to get rid of grep in `packages/android-performance-profiler/src/commands/detectCurrentAppBundleId.ts`)
(➡️ should work out of the box after previous fixes)
(➡️ in `packages/e2e-performance/src/executeAsync.ts` if platform == win32, don't use `script -q`, just use `spawn(command.split(" ")[0], command.split(" ").slice(1))`
(➡️ would it be simple enough to use Scoop or a similar install script? https://scoop.sh/)
> feat: add windows support

- packages/android-performance-profiler/src/commands/cppProfiler.ts
See https://github.com/bamlab/flashlight/issues/103
> fix(profiler): fix buffer overflow when running atrace async_stop

- packages/web-reporter-ui/src/components/Chart.tsx
- packages/web-reporter-ui/src/sections/CPUReport.tsx
- packages/web-reporter-ui/src/sections/FPSReport.tsx
> feat: ✨ Add danger and safe zone to charts

- packages/flipper-plugin-android-performance-profiler/src/__tests__/__snapshots__/Plugin.ts.snap
- packages/web-reporter-ui/__tests__/__snapshots__/ReporterView.test.tsx.snap
- packages/web-reporter-ui/src/components/Header.tsx
I don't why but it seems that the classnames from MUI was overriding the classname from tailwind on the parent. But when putting the tailwind classname on the icon itself it's not overridden 🙃 
So, to remember : the dev should be always putting the `fill-color-00` or `stroke-color-00` on the svg itself (as low as possible)
I still don't know why it was working here but not in flashlight-cloud
> fix: put the color class name on the icon and not the container

- packages/measure/src/webapp/socket.ts
Since `flashlight measure` opens a new webapp on a new tab everytime, we want to make sure this one is the only one connected to the cli, so we completely close any previous webapp connection when it gets disconnected
Otherwise, this scenario can happen:
- I run `flashlight measure`, opening tab 1 
- i cancel the command
- I run `flashlight measure` again, opening a new tab
- the new tab connects to the CLI
- then the previous tab connects as well, and since we only allow one socket connection, the new tab we're using gets disconnected <= this is what we want to prevent
it would be possible to handle having multiple web apps connected to the socket, but for now it's just easier to manage this way
> fix(measure): ensure we have only one socket connection between web & cli

- README.md
Added a quick copy/paste installation command section on the readme for those who are familiar with the docs but just came here to grab the install
> docs(readme): added install cmds

- packages/commands/test/src/executeAsync.ts
Fixes #148 
Can reproduce the bug after upgrading to Sonoma 14.0, but somehow not before 🤔 haven't verified in dept, I prefered to completely simplify the logic here and that fixes the bug.
This brings us another fix: adding `&&` in `testCommand` now works (like `--testCommand "sleep 5 && adb shell am start com.example/.MainActivity" for instance)
One caveat is we lose the nice Maestro formatting, but I think that's an acceptable loss, given that it was always clearing the terminal on each iteration anyway Now we have the same output as using `maestro` with `--no-ansi`
This is what it looks like now:
> fix(test): fix Operation not supported on socket

- package.json
- yarn.lock
lint-staged newer versions require node 18. 
Not an ideal fix, however:
We run `npm-bundle` on the whole repo before sending it to AWS as per their doc, however it seems it doesn't package installed dependencies as expected. Since the lock file isn't included, we reinstall all deps on AWS, hence hitting an issue
Note that installing node 18 on AWS Device farm machines fails with error: node: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by node)
> chore: fix e2e Android ci

- .github/workflows/tests.yml
- packages/platforms/android/src/commands/cpu/__tests__/getCpuStatsByProcess.test.ts
- packages/platforms/android/src/commands/cpu/getCpuStatsByProcess.ts
[for this issues](https://github.com/bamlab/flashlight/issues/179)
I have run the test.
Maybe you can checkout that this commit is correct.
thanks for that.
> fix(getCpuStatsByProcess): fix regex for CPU stats

- package.json
- packages/commands/measure/src/__tests__/measure.test.tsx
- packages/commands/measure/src/server/ServerApp.tsx
- packages/commands/measure/src/server/ServerSocketConnectionApp.tsx
- packages/commands/measure/src/server/bin.tsx
- packages/commands/measure/src/server/components/HostAndPortInfo.tsx
- packages/commands/measure/src/server/constants.ts
This PR introduces a new feature to the measure command, allowing users to specify a custom port for the server using the --port flag. This enhancement provides greater flexibility in environments where the default port (`3000`) might be unavailable or conflicts with other services.
- Added --port flag to the measure command.
- Implemented logic to parse and utilize the custom port value within the ServerApp.
- Updated relevant tests to cover the new feature, ensuring the custom port is correctly handled.
This update empowers users with the ability to set up the server on a port of their choice, enhancing the tool's usability in diverse development setups. It is a backward-compatible change, maintaining the default port setting when the flag is not used.
> chore(measure): add optional --port flag to specify server port

- jest.config.js
- packages/commands/measure/package.json
- packages/commands/measure/src/__tests__/measure.test.tsx
- packages/commands/measure/src/__tests__/server/ServerApp.test.ts
- packages/commands/measure/src/__tests__/webapp/socket.test.ts
- packages/commands/measure/src/common/types/index.d.ts
- packages/commands/measure/src/server/ServerApp.tsx
- packages/commands/measure/src/webapp/globals.d.ts
- packages/commands/measure/src/webapp/index.html
- packages/commands/measure/src/webapp/socket.ts
- yarn.lock
This PR is a follow-up to https://github.com/bamlab/flashlight/pull/186 addressing [this issue comment](https://github.com/bamlab/flashlight/pull/186#issuecomment-1893458782).
The issue was caused by the webapp connecting to a fixed socket server url (`http://localhost:3000`). To resolve this, we server-side render data into a (`__FLASHLIGHT_DATA__`) object, which is now available in the window context of the webapp. This change enables the webapp's socket client to connect to a dynamic server url.
A notable aspect of this change is its impact on unit testing, particularly for the `MeasureWebApp` component. Related tests now require setting up the `window.__FLASHLIGHT_DATA__` context _before_ importing `MeasureWebApp`. This is crucial because if …
> fix(measure): UI buttons unresponsive/streamline socket URL handling

- packages/commands/measure/src/__tests__/server/ServerApp.test.ts
- packages/commands/measure/src/server/ServerApp.tsx
- packages/commands/measure/src/webapp/index.html
When building the Flashlight CLI, for some reason the comment in the HTML file got removed Actually it's unclear to me why it wasn't getting removed before, now at least we're sure that this will never get removed by parcel
> fix(measure): fix port option

- package.json
- yarn.lock
Since we install the whole project on AWS CI, we are faced with 2 issues:
- the yarn.lock file doesn't get packages when we push dependencies with npm-bundle
- AWS doesn't support node 18 so is still running Node 16
Husky v9 doesn't support node 16, so ensuring we install node 16 as a quick fix
> chore: fix aws CI

- CHANGELOG.md
`CHANGELOG.md` had different title levels for different versions. I set the same level for all versions.
In addition, I added the diff for versions where it was missing.
> docs: Harmonize the CHANGELOG.md file

- packages/core/reporter/src/index.ts
We are integrating `flashlisght` profiler to our e2e tests pipeline and we would like to capture average FPS and RAM usage.
So I'm exporting everything from these files as it was done with `cpu` file.
> feat: export FPS and RAM reporting

- packages/plugins/appium-helper/AppiumDriver.ts
- packages/plugins/appium-helper/README.md
Running tests that rely on the plugin strictly following the README steps causes us to face issues preventing us from properly creating an Appium driver session.
Some causes could relate to not installing drivers and compatibility issues using Appium 2.0. The client code seems to be outdated.
* README updated to include instructions about the driver installation
* Fixed driver basepath by removing /wd/hub that doesn't exist anymore
* Fixed capabilities definition by adding the required vendor prefix
| server console | test console |
| --------------- | ---------------- |
| ![Untitled (1)](https://github.com/user-attachments/assets/83f4c36d-dd67-41bf-add7-6326221a1b5d) | ![Untitled (2)](https://github.com/user-attachments/assets/8c194a71-6d94-4345-9f5d-017715fbb76b) |
| server console | …
> Fix appium-helper's client code to run with Appium v2.0+ properly

- packages/plugins/aws-device-farm/src/commands/checkResults.ts
- packages/plugins/aws-device-farm/src/commands/runTest.ts
This prevents a bug in Flashlight Cloud where Flashlight would get stuck in the processing video phases for longer tests
> fix(aws): remove video processing since we switched to newer phones
